<?php
global $cfg_Cs;
$cfg_Cs=array();
$cfg_Cs[1]=array(0,1,1,'1b6zpNDCzsU=');
$cfg_Cs[2]=array(0,1,1,'zfjVvtPFu68=');
$cfg_Cs[3]=array(0,1,1,'zca549Oq1Ms=');
$cfg_Cs[4]=array(0,1,1,'vq3R6b3Ms8w=');
$cfg_Cs[8]=array(0,1,1,'1b6zpNeozLg=');
$cfg_Cs[9]=array(0,1,1,'vajVvr27wfc=');
$cfg_Cs[36]=array(0,1,1,'zfjC57S00rU=');
$cfg_Cs[41]=array(0,1,1,'ssbJ8deowLg=');
$cfg_Cs[27]=array(0,1,1,'1LTC67PM0PI=');
$cfg_Cs[39]=array(0,1,1,'tefJzM34teo=');
?>