<field:body itemname="文章内容" autofield="0" notsend="0" type="htmltext" isnull="true" islist="1" default=""  maxlength="" page="split">	
</field:body>	
<field:huandeng itemname="F幻灯300*225" autofield="1" notsend="0" type="imgfile" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:huandeng>

<field:lianxi itemname="联系方法" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:lianxi>


<field:gou itemname="购买地址" autofield="1" notsend="0" type="multitext" isnull="true" islist="1" default=""  maxlength="500" page="">
</field:gou>




<field:jiage itemname="价格" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:jiage>


<field:yanshi itemname="演示地址" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:yanshi>

<field:hxin itemname="核心程序" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:hxin>
