<dl>
          <dt><a title=[field:title/] href="[field:arcurl/]" target=_blank><img alt=[field:title/] src="[field:litpic/]" /></a> </dt>
          <dd class=textname><a title=[field:title/] href="[field:arcurl/]" target="_blank">[field:title/]</a> </dd>
          <dd class=texttxt title="[field:info/]">[field:info/]бн
            <div style="CLEAR: both"></div>


          </dd>
        </dl>