<item>
    <title><![CDATA[[field:title/]]]></title>
    <link>[field:fullurl function='str_replace("http://www.huchuan6.comhttp://","http://",@me)'/]</link>
    <description><![CDATA[[field:description function='html2text(@me)'/]...<br /><b>文章分类</b>:<a href="[field:typeurl/]" target="_blank">[field:typename/]</a><br /><a href="[field:arcurl/]" target="_blank">阅读全文</a> | <a href="http://www.huchuan6.com/plus/recommend.php?aid=[field:id/]" target="_blank">邮件推荐</a> | <a href="[field:arcurl/]" target="_blank">评论回复</a>]]></description>
    <pubDate>[field:stime/]</pubDate>
    <category>[field:typename/]</category>
    <author>[field:writer/]</author>
    <comments>[field:source/]</comments>
</item>