<?php
$z[0]=Array("global","",744,770);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",859,885);
$z[1][4]['name']="cfg_cmspath";
$z[2]=Array("channel","\r\n        \r\n        <li><a href='[field:typeurl/]'>[field:typename/]</a></li>\r\n        \r\n         	",1813,2038);
$z[2][4]['row']="12";
$z[2][4]['type']="top";
$z[2][4]['currentstyle']="<li><a class='cr' href='~typelink~' ~rel~>~typename~</a></li>";

?>