<?php
if(!isset($GLOBALS['_vars'])) $GLOBALS['_vars'] = array(); 
$fields = array();
?><!-- //底部模板 -->
<div class="footer w960 center mt1 clear">
	
    <div class="footer_left"></div>
    <div class="footer_body">
	<p class="powered">    
		Powered by 互传站长网 &copy; 20013-2014  Inc.<br /><div class="copyright">互传站长网-HuChuan6.com 版权所有&nbsp;&nbsp;<?php echo $GLOBALS['cfg_beian']; ?></div></p>        
<!-- /powered -->
   </div>
   <div class="footer_right"></div>
</div>